WITH REF_STG_CROSSREF_ARTICLE AS (SELECT * FROM {{ ref('STG_CROSSREF_ARTICLE') }})
SELECT DISTINCT ARTICLE_SID
              , ARTICLE_DOI
              , ARTICLE_URL
              , ARTICLE_TITLE
              , ARTICLE_SHORT_TITLE
              , ARTICLE_SUBTITLE
              , ARTICLE_ABSTRACT
              , ARTICLE_EST_PUBLISH_DT AS ARTICLE_PUBLICATION_DT
FROM REF_STG_CROSSREF_ARTICLE