WITH REF_STG_CROSSREF_AUTHOR AS (SELECT * FROM {{ ref('STG_CROSSREF_AUTHOR') }})
SELECT DISTINCT AUTHOR_SID
              , IF(AUTHOR_FULL_NAME = '', 'n/a', AUTHOR_FULL_NAME) AS AUTHOR_FULL_NAME
              , IFNULL(AUTHOR_ORCID_ID, 'n/a')                     AS AUTHOR_ORCID_ID
FROM REF_STG_CROSSREF_AUTHOR