WITH REF_STG_CROSSREF_ARTICLE AS (SELECT * FROM {{ ref('STG_CROSSREF_ARTICLE') }})
SELECT DISTINCT ARTICLE_SID
              , ARTICLE_DOI
              , ARTICLE_URL
              , IFNULL(ARTICLE_FUNDER, 'n/a')                AS ARTICLE_FUNDER
              , IFNULL(ARTICLE_INSTITUTION, 'n/a')           AS ARTICLE_INSTITUTION
              , IFNULL(ARTICLE_PUBLISHER, 'n/a')             AS ARTICLE_PUBLISHER
              , IFNULL(ARTICLE_TITLE, 'n/a')                 AS ARTICLE_TITLE
              , IFNULL(ARTICLE_SHORT_TITLE, 'n/a')           AS ARTICLE_SHORT_TITLE
              , IFNULL(ARTICLE_SUBTITLE, 'n/a')              AS ARTICLE_SUBTITLE
              , IFNULL(ARTICLE_ORIGINAL_TITLE, 'n/a')        AS ARTICLE_ORIGINAL_TITLE
              , IFNULL(ARTICLE_CONTAINER_TITLE, 'n/a')       AS ARTICLE_CONTAINER_TITLE
              , IFNULL(ARTICLE_SHORT_CONTAINER_TITLE, 'n/a') AS ARTICLE_SHORT_CONTAINER_TITLE
              , IFNULL(ARTICLE_ABSTRACT, 'n/a')              AS ARTICLE_ABSTRACT
              , ARTICLE_EST_PUBLISH_DT                       AS ARTICLE_PUBLICATION_DT
FROM REF_STG_CROSSREF_ARTICLE