WITH REF_STG_CROSSREF_AUTHOR AS (SELECT * FROM {{ ref('STG_CROSSREF_AUTHOR') }}),
     REF_ANALYTICS_AUTHOR_COLLABORATIVENESS AS (SELECT * FROM {{ source('ANALYTICS', 'AUTHOR_COLLABORATIVENESS') }})
SELECT DISTINCT A.AUTHOR_SID
              , IF(A.AUTHOR_FULL_NAME = '', 'n/a', A.AUTHOR_FULL_NAME) AS AUTHOR_FULL_NAME
              , IFNULL(A.AUTHOR_ORCID_ID, 'n/a')                       AS AUTHOR_ORCID_ID
              , IFNULL(AC.IS_AUTHOR_MORE_COLLABORATIVE, FALSE)         AS IS_AUTHOR_MORE_COLLABORATIVE
FROM REF_STG_CROSSREF_AUTHOR A
         LEFT JOIN REF_ANALYTICS_AUTHOR_COLLABORATIVENESS AC USING (AUTHOR_SID)