WITH REF_STG_CROSSREF_ARTICLE AS (SELECT * FROM {{ ref('STG_CROSSREF_ARTICLE') }}),
     REF_ANALYTICS_ARTICLE_LANGUAGE AS (SELECT * FROM {{ source('ANALYTICS', 'ARTICLE_LANGUAGE') }})
SELECT DISTINCT A.ARTICLE_SID
              , A.ARTICLE_DOI
              , A.ARTICLE_URL
              , IFNULL(A.ARTICLE_FUNDER, 'n/a')                AS ARTICLE_FUNDER
              , IFNULL(A.ARTICLE_INSTITUTION, 'n/a')           AS ARTICLE_INSTITUTION
              , IFNULL(A.ARTICLE_PUBLISHER, 'n/a')             AS ARTICLE_PUBLISHER
              , IFNULL(A.ARTICLE_TITLE, 'n/a')                 AS ARTICLE_TITLE
              , IFNULL(A.ARTICLE_SHORT_TITLE, 'n/a')           AS ARTICLE_SHORT_TITLE
              , IFNULL(A.ARTICLE_SUBTITLE, 'n/a')              AS ARTICLE_SUBTITLE
              , IFNULL(A.ARTICLE_ORIGINAL_TITLE, 'n/a')        AS ARTICLE_ORIGINAL_TITLE
              , IFNULL(A.ARTICLE_CONTAINER_TITLE, 'n/a')       AS ARTICLE_CONTAINER_TITLE
              , IFNULL(A.ARTICLE_SHORT_CONTAINER_TITLE, 'n/a') AS ARTICLE_SHORT_CONTAINER_TITLE
              , IFNULL(A.ARTICLE_ABSTRACT, 'n/a')              AS ARTICLE_ABSTRACT
              , IFNULL(A.ARTICLE_REFERENCE, 'n/a')             AS ARTICLE_REFERENCE
              , IFNULL(L.ARTICLE_LANGUAGE, 'n/a')              AS ARTICLE_LANGUAGE
              , A.ARTICLE_EST_PUBLISH_DT                       AS ARTICLE_PUBLICATION_DT
FROM REF_STG_CROSSREF_ARTICLE A
         LEFT JOIN REF_ANALYTICS_ARTICLE_LANGUAGE L USING (ARTICLE_DOI)