WITH REF_STG_EUTOPIA_INSTITUTION AS (SELECT * FROM {{ ref('STG_EUTOPIA_INSTITUTION') }})
SELECT INSTITUTION_SID,
       INSTITUTION_NAME,
       INSTITUTION_PRETTY_NAME,
       INSTITUTION_COUNTRY,
       INSTITUTION_LANGUAGE,
       INSTITUTION_COUNTRY_ISO2
FROM REF_STG_EUTOPIA_INSTITUTION
UNION ALL
SELECT 'n/a' AS INSTITUTION_SID,
       'n/a' AS INSTITUTION_NAME,
       'n/a' AS INSTITUTION_PRETTY_NAME,
       'n/a' AS INSTITUTION_COUNTRY,
       'n/a' AS INSTITUTION_LANGUAGE,
       'n/a' AS INSTITUTION_COUNTRY_ISO2
UNION ALL
SELECT 'OTHER'              AS INSTITUTION_SID,
       'Other Institutions' AS INSTITUTION_NAME,
       'Other Institutions' AS INSTITUTION_PRETTY_NAME,
       'n/a'                AS INSTITUTION_COUNTRY,
       'n/a'                AS INSTITUTION_LANGUAGE,
       'n/a'                AS INSTITUTION_COUNTRY_ISO2
