WITH REF_STG_CROSSREF_AUTHOR AS (SELECT * FROM {{ ref('STG_CROSSREF_AUTHOR') }})
SELECT DISTINCT AUTHOR_SID
              , AUTHOR_FULL_NAME
              , AUTHOR_ORCID_ID
FROM REF_STG_CROSSREF_AUTHOR