WITH REF_STG_CERIF_RESEARCH_TOPIC AS (SELECT * FROM {{ ref('STG_CERIF_RESEARCH_TOPIC') }})
SELECT DATALAKE.UDF_MD5_HASH([RESEARCH_TOPIC_CODE]) AS RESEARCH_TOPIC_SID,
       RESEARCH_BRANCH_CODE,
       RESEARCH_BRANCH_NAME,
       RESEARCH_SUBBRANCH_CODE,
       RESEARCH_SUBBRANCH_NAME,
       RESEARCH_TOPIC_CODE,
       RESEARCH_TOPIC_NAME
FROM REF_STG_CERIF_RESEARCH_TOPIC