PATH_TO_SECRETS_FILE: 'secrets/secrets.yml'
RANDOM_SEED: 42
GCP:
  PROJECT_ID: 'collaboration-recommender'
  READ_SCHEMA: "DBT_DEV"
  INGESTION_SCHEMA: "DATALAKE"
  ANALYTICS_SCHEMA: "ANALYTICS"
TEXT_EMBEDDING:
  MODEL_NAME: 'allenai/scibert_scivocab_cased'
HISTORIC:
  CROSSREF:
    DATA_FOLDER_PATH: 'data/April 2024 Public Data File from Crossref'
    TARGET_TABLE_NAME: 'CROSSREF_HISTORIC_ARTICLE'
    N_MAX_RECORDS: null
    N_MAX_ITERATIONS_TO_OFFLOAD: 500
    START_ITERATION: 0
  CROSSREF_REFERENCE_ARTICLES:
    TARGET_TABLE_NAME: 'CROSSREF_API_REFERENCE_ARTICLE'
    N_MAX_RECORDS: null
    N_MAX_ITERATIONS_TO_OFFLOAD: 500
    START_ITERATION: 0
  EUTOPIA:
    TARGET_TABLE_NAME: 'EUTOPIA_INSTITUTION'
  ORCID_TARFILE:
    FILE_PATH: 'data/ORCID_2023_10_summaries.tar.gz'
    TARGET_TABLE_NAME: 'ORCID_HISTORIC_AUTHOR'
    N_MAX_RECORDS: null
    START_ITERATION: 0
  CERIF:
    PATH_TO_HTML_FILE: 'data/cerif.html'
    TARGET_TABLE_NAME: 'CERIF_RESEARCH_TOPIC'
  CERIF_RESEARCH_TOPIC_TOP_N_ARTICLES:
    TARGET_TABLE_NAME: 'CERIF_RESEARCH_TOPIC_TOP_N_ARTICLES'
    N_ARTICLES: 16
  ORCID_API:
    TARGET_TABLE_NAME: 'ORCID_API_AUTHOR'
    N_MAX_RECORDS: null
    N_MAX_ITERATIONS_TO_OFFLOAD: 1000
  UNPAYWALL:
    TARGET_TABLE_NAME: 'UNPAYWALL_API_ARTICLE'
    N_MAX_RECORDS: null
    N_MAX_ITERATIONS_TO_OFFLOAD: 1000
EMBEDDING:
  RESEARCH_TOPIC_METADATA:
    SOURCE_TABLE_NAME: 'EMBEDDING_RESEARCH_TOPIC'
    TARGET_TABLE_NAME: 'TEXT_EMBEDDING_RESEARCH_TOPIC_METADATA'
    BATCH_SIZE: 8
  RESEARCH_TOPIC_TOP_N_ARTICLES:
    SOURCE_TABLE_NAME: 'EMBEDDING_RESEARCH_TOPIC_TOP_N_ARTICLES'
    TARGET_TABLE_NAME: 'TEXT_EMBEDDING_RESEARCH_TOPIC_TOP_N_ARTICLES'
    BATCH_SIZE: 8
    N_MAX_RECORDS: null
    N_MAX_ITERATIONS_TO_OFFLOAD: 30
  RESEARCH_TOPIC_COMBINED:
    TARGET_TABLE_NAME: 'TEXT_EMBEDDING_RESEARCH_TOPIC'
  ARTICLE:
    SOURCE_TABLE_NAME: 'EMBEDDING_ARTICLE'
    TARGET_TABLE_NAME: 'TEXT_EMBEDDING_ARTICLE'
    BATCH_SIZE: 8
    N_MAX_RECORDS: null
    N_MAX_ITERATIONS_TO_OFFLOAD: 30
    SUPPORTED_LANGUAGES:
      - 'en'
ANALYTICS:
  COLLABORATION_NOVELTY:
    SOURCE_TABLE_NAME: 'INT_COLLABORATION'
    TARGET_TABLE_NAME: 'COLLABORATION_NOVELTY'
    N_MAX_ITERATIONS_TO_OFFLOAD: 3
  ARTICLE_TOPIC:
    SOURCE_TABLE_NAME_TOPIC_EMBEDDING: 'TEXT_EMBEDDING_RESEARCH_TOPIC'
    SOURCE_TABLE_NAME_ARTICLE_EMBEDDING: 'TEXT_EMBEDDING_ARTICLE'
    TARGET_TABLE_NAME: 'ARTICLE_TOPIC'
  ARTICLE_LANGUAGE:
    SOURCE_TABLE_NAME: 'EMBEDDING_ARTICLE'
    TARGET_TABLE_NAME: 'ARTICLE_LANGUAGE'
    N_MAX_ITERATIONS_TO_OFFLOAD: 1000
    N_MAX_RECORDS: null
DASHBOARD:
  REDIS_URL: 'redis://localhost:6379'
  VERBOSE: true
  COLORS:
    BACKGROUND_COLOR: '#f8f9fa'
    TEXT_COLOR: '#000d3b'
    GOOD_COLOR: '#43AA8B'
    BAD_COLOR: '#EF3054'
    WARNING_COLOR: '#feed72'
    CLASS_COLORS:
      - '#00a9e0'
