name: C:\conda-envs\eutopia-env3
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz=0.18.0
  - asttokens=2.0.5
  - blas=1.0
  - blas-devel=3.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - cairo=1.18.0
  - certifi=2024.6.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - cons=0.4.6
  - contourpy=1.2.1
  - cycler=0.12.1
  - dash=2.17.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - deprecated=1.2.13
  - dm-tree=0.1.8
  - etuples=0.3.9
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.2
  - filelock=3.14.0
  - flask=3.0.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - getopt-win32=0.1
  - graphite2=1.3.13
  - graphviz=11.0.0
  - gts=0.7.6
  - h5netcdf=1.3.0
  - h5py=3.11.0
  - harfbuzz=8.5.0
  - hdf5=1.14.3
  - icu=73.2
  - ipykernel=6.28.0
  - ipython=8.20.0
  - itsdangerous=2.2.0
  - jedi=0.18.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgd=2.3.3
  - libglib=2.80.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.43
  - libpython=2.2
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.3.1
  - logical-unification=0.4.6
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-toolchain_win-64=2.5.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - markdown-it-py=3.0.0
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - minikanren=1.0.3
  - mkl-devel=2023.2.0
  - mkl-include=2023.2.0
  - mkl-service=2.4.1
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.0
  - pandas=2.2.2
  - pango=1.52.2
  - parso=0.8.3
  - patsy=0.5.6
  - pcre2=10.43
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.4
  - platformdirs=3.10.0
  - plotly=5.22.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pygments=2.18.0
  - pymc=5.15.1
  - pymc-base=5.15.1
  - pyparsing=3.1.2
  - pytensor=2.22.1
  - pytensor-base=2.22.1
  - python=3.10.14
  - python-box=7.1.1
  - python-dateutil=2.9.0
  - python-graphviz=0.20.3
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - pywin32=305
  - pyzmq=25.1.2
  - redis-py=4.3.4
  - retrying=1.3.3
  - rich=13.7.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=70.0.0
  - six=1.16.0
  - stack_data=0.2.0
  - statsmodels=0.14.2
  - tenacity=8.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - toolz=0.12.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.5
  - werkzeug=3.0.3
  - wheel=0.43.0
  - wrapt=1.14.1
  - xarray=2024.5.0
  - xarray-einstats=0.7.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.0
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.8.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - dash-bootstrap-components==1.6.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - db-dtypes==1.2.0
      - defusedxml==0.7.1
      - fastjsonschema==2.19.1
      - fqdn==1.5.1
      - fsspec==2024.2.0
      - google-api-core==2.19.0
      - google-auth==2.30.0
      - google-cloud-bigquery==3.24.0
      - google-cloud-bigquery-storage==2.25.0
      - google-cloud-core==2.4.1
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.0
      - googleapis-common-protos==1.63.1
      - grpcio==1.64.1
      - grpcio-status==1.62.2
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - importlib-metadata==7.1.0
      - intel-openmp==2021.4.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jinja2==3.1.3
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - langdetect==1.0.9
      - markupsafe==2.1.5
      - mistune==3.0.2
      - mkl==2021.4.0
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.2.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - prometheus-client==0.20.0
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - pyarrow==16.1.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - python-json-logger==2.0.7
      - pywinpty==2.0.13
      - pyyaml==6.0.1
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - rsa==4.9
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.5
      - sympy==1.12
      - tbb==2021.11.0
      - terminado==0.18.1
      - tinycss2==1.3.0
      - tomli==2.0.1
      - torch==2.3.1+cpu
      - torchaudio==2.3.1+cpu
      - torchvision==0.18.1+cpu
      - tqdm==4.66.4
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - urllib3==2.2.1
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11
      - xmltodict==0.13.0
      - zipp==3.19.2
