WITH REF_ARTICLE_TOPIC AS (SELECT *
                           FROM {{ source('ANALYTICS', 'ARTICLE_TOPIC') }})

SELECT DATALAKE.UDF_MD5_HASH([DOI]) AS ARTICLE_SID
     , RESEARCH_TOPIC_CODE
     , RANK
FROM REF_ARTICLE_TOPIC