WITH REF_INT_COLLABORATION AS (SELECT *
                               FROM {{ ref('INT_COLLABORATION') }})
   , REF_COLLABORATION_NOVELTY_METADATA AS (SELECT *
                                            FROM {{ source('ANALYTICS', 'COLLABORATION_NOVELTY_METADATA') }})
   , REF_DIM_ARTICLE AS (SELECT *
                         FROM {{ ref('DIM_ARTICLE') }})
SELECT C.ARTICLE_SID,
       C.AUTHOR_SID,
       C.INSTITUTION_SID,
       C.ARTICLE_PUBLICATION_DT,
       C.IS_SOLE_AUTHOR_PUBLICATION,
       C.IS_INTERNAL_COLLABORATION,
       C.IS_EXTERNAL_COLLABORATION,
       C.IS_EUTOPIAN_COLLABORATION,
       C.IS_EUTOPIAN_PUBLICATION,
       IF(C.INSTITUTION_SID <> 'n/a'
              AND C.AUTHOR_SID <> 'n/a'
              AND NOT C.IS_SOLE_AUTHOR_PUBLICATION
              AND EXTRACT(YEAR FROM C.ARTICLE_PUBLICATION_DT) >= 2000,
          CN.IS_NEW_AUTHOR_COLLABORATION, FALSE)                               AS IS_NEW_AUTHOR_COLLABORATION,
       IF(C.INSTITUTION_SID <> 'n/a'
              AND C.AUTHOR_SID <> 'n/a'
              AND NOT C.IS_SOLE_AUTHOR_PUBLICATION
              AND EXTRACT(YEAR FROM C.ARTICLE_PUBLICATION_DT) >= 2000,
          CN.IS_NEW_INSTITUTION_COLLABORATION, FALSE)                          AS IS_NEW_INSTITUTION_COLLABORATION,
       IFNULL(A.IS_ARTICLE_RELEVANT, FALSE)                                    AS IS_ARTICLE_RELEVANT,
       DATALAKE.UDF_MD5_HASH([C.ARTICLE_SID, C.AUTHOR_SID, C.INSTITUTION_SID]) AS PK_COLLABORATION
FROM REF_INT_COLLABORATION C
         LEFT JOIN REF_COLLABORATION_NOVELTY_METADATA CN
                   ON C.ARTICLE_SID = CN.ARTICLE_SID
                       AND C.AUTHOR_SID = CN.AUTHOR_SID
                       AND C.INSTITUTION_SID = CN.INSTITUTION_SID
         LEFT JOIN REF_DIM_ARTICLE A ON C.ARTICLE_SID = A.ARTICLE_SID
