WITH REF_COLLABORATION_NOVELTY_INDEX AS (SELECT *
                                         FROM {{ source('ANALYTICS', 'COLLABORATION_NOVELTY_INDEX') }})
   , SOLE_AUTHOR_COLLABORATION AS (SELECT DISTINCT ARTICLE_SID
                                   FROM {{ ref('FCT_COLLABORATION') }}
                                   WHERE IS_SOLE_AUTHOR_PUBLICATION)
SELECT CN.ARTICLE_SID,
       CN.COLLABORATION_NOVELTY_INDEX,
       DATALAKE.UDF_MD5_HASH([CN.ARTICLE_SID]) AS PK_COLLABORATION_NOVELTY
FROM REF_COLLABORATION_NOVELTY_INDEX CN
         LEFT JOIN SOLE_AUTHOR_COLLABORATION S USING (ARTICLE_SID)
WHERE S.ARTICLE_SID IS NULL