WITH REF_INT_COLLABORATION AS (SELECT *
                               FROM {{ ref('INT_COLLABORATION') }})
   , REF_COLLABORATION_NOVELTY AS (SELECT *
                                   FROM {{ source('ANALYTICS', 'COLLABORATION_NOVELTY') }})
SELECT C.ARTICLE_SID,
       C.AUTHOR_SID,
       C.INSTITUTION_SID,
       C.ARTICLE_PUBLICATION_DT,
       C.IS_SOLE_AUTHOR_PUBLICATION,
       C.IS_INTERNAL_COLLABORATION,
       C.IS_EXTERNAL_COLLABORATION,
       C.IS_EUTOPIAN_COLLABORATION,
       C.IS_EUTOPIAN_PUBLICATION,
       CN.IS_NEW_COLLABORATION
FROM REF_INT_COLLABORATION C
         LEFT JOIN REF_COLLABORATION_NOVELTY CN USING (ARTICLE_SID)
