WITH REF_COLLABORATION_NOVELTY_INDEX AS (SELECT *
                                         FROM {{ source('ANALYTICS', 'COLLABORATION_NOVELTY_INDEX') }})
   , SOLE_AUTHOR_COLLABORATION AS (SELECT DISTINCT ARTICLE_SID,
                                                   IS_SOLE_AUTHOR_PUBLICATION,
                                                   ARTICLE_PUBLICATION_DT
                                   FROM {{ ref('FCT_COLLABORATION') }})
SELECT CN.ARTICLE_SID,
       CN.COLLABORATION_NOVELTY_INDEX,
       S.ARTICLE_PUBLICATION_DT,
       DATALAKE.UDF_MD5_HASH([CN.ARTICLE_SID]) AS PK_COLLABORATION_NOVELTY
FROM REF_COLLABORATION_NOVELTY_INDEX CN
         LEFT JOIN SOLE_AUTHOR_COLLABORATION S USING (ARTICLE_SID)
WHERE NOT S.IS_SOLE_AUTHOR_PUBLICATION
GROUP BY 1, 2, 3, 4