WITH REF_COLLABORATION_NOVELTY AS (SELECT *
                                   FROM {{ source('ANALYTICS', 'COLLABORATION_NOVELTY') }})
SELECT ARTICLE_SID,
       COLLABORATION_NOVELTY_INDEX,
       IS_NEW_COLLABORATION
FROM REF_COLLABORATION_NOVELTY