WITH REF_ARTICLE_TOPIC AS (SELECT *
                           FROM {{ source('ANALYTICS', 'ARTICLE_TOPIC') }}),
     REF_DIM_RESEARCH_TOPIC AS (SELECT *
                                FROM {{ ref('DIM_RESEARCH_TOPIC') }})

SELECT DATALAKE.UDF_MD5_HASH([A.DOI])                        AS ARTICLE_SID
     , RT.RESEARCH_TOPIC_SID
     , A.RANK
     , DATALAKE.UDF_MD5_HASH([A.DOI, RT.RESEARCH_TOPIC_SID]) AS PK_ARTICLE_TOPIC
FROM REF_ARTICLE_TOPIC A
         LEFT JOIN REF_DIM_RESEARCH_TOPIC RT USING (RESEARCH_TOPIC_CODE)