CREATE OR REPLACE TABLE `collaboration-recommender`.DATALAKE.CERIF_RESEARCH_TOPIC
(
    RESEARCH_BRANCH_CODE    STRING,
    RESEARCH_BRANCH_NAME    STRING,
    RESEARCH_SUBBRANCH_CODE STRING,
    RESEARCH_SUBBRANCH_NAME STRING,
    RESEARCH_TOPIC_CODE     STRING,
    RESEARCH_TOPIC_NAME     STRING
);

