CREATE OR REPLACE TABLE `collaboration-recommender`.ANALYTICS.COLLABORATION_NOVELTY
(
    ARTICLE_SID                 STRING,
    IS_NEW_COLLABORATION           BOOL,
    COLLABORATION_NOVELTY_INDEX FLOAT64
);

