CREATE OR REPLACE TABLE `collaboration-recommender`.ANALYTICS.TEXT_EMBEDDING_RESEARCH_TOPIC_TOP_N_ARTICLES
(
    RESEARCH_TOPIC_CODE    STRING,
    ARTICLE_DOI            STRING,
    EMBEDDING_TENSOR_SHAPE ARRAY <INT64>,
    EMBEDDING_TENSOR_DATA  ARRAY <FLOAT64>
);
