WITH REF_STG_CROSSREF_DOI_METADATA AS (SELECT *
                                       FROM {{ source('DATALAKE', 'CROSSREF_HISTORIC_ARTICLE_PROCESSED') }})
SELECT ARTICLE_SID
     , ARTICLE_DOI
     , ARTICLE_URL
     , ARTICLE_FUNDER
     , ARTICLE_INSTITUTION
     , ARTICLE_PUBLISHER
     , ARTICLE_TITLE
     , ARTICLE_SHORT_TITLE
     , ARTICLE_SUBTITLE
     , ARTICLE_ORIGINAL_TITLE
     , ARTICLE_CONTAINER_TITLE
     , ARTICLE_SHORT_CONTAINER_TITLE
     , ARTICLE_ABSTRACT
     , ARTICLE_REFERENCE
     , ARTICLE_EST_PUBLISH_DT
FROM REF_STG_CROSSREF_DOI_METADATA