WITH REF_STG_CERIF_RESEARCH_TOPIC AS (SELECT *
                                      FROM {{ source('DATALAKE', 'CERIF_RESEARCH_TOPIC') }})
SELECT RESEARCH_BRANCH_CODE,
       RESEARCH_BRANCH_NAME,
       RESEARCH_SUBBRANCH_CODE,
       RESEARCH_SUBBRANCH_NAME,
       RESEARCH_TOPIC_CODE,
       RESEARCH_TOPIC_NAME
FROM REF_STG_CERIF_RESEARCH_TOPIC